[platformio]
extra_configs = secrets.ini

[env:elecrow-esp32s3-epaper-579]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_port = /dev/ttyUSB0
board_build.flash_size = 8MB
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3
    -DWIFI_SSID=\"${secrets.wifi_ssid}\"
    -DWIFI_PASSWORD=\"${secrets.wifi_password}\"
    -DCONFIG_API_URL=\"${secrets.config_api_url}\"
lib_extra_dirs = lib
lib_deps =
    bblanchon/ArduinoJson@^7.3.1
